# If disabled, the bottle will be consumed when a player right-click it
throwable: true

# The lowest XP a player can withdraw
minimum_exp: 50
# The highest XP a player can withdraw
maximum_exp: 999999

# Tax will deduct the total amount goes to the bottle.
# For example, if tax is enabled and at the rate of 10%,
# if a player withdraws 1000 XP, the bottle will have 900.
tax: false
# Decimal form, e.g 0.1 = 10%
tax_amount: 0.1

# XP Bottle information
bottle:
  name: '&aXP Bottle'
  lore:
  - '&9Creator: &r%playerdisplayname%'
  - '&9XP: &a%xp%'

# Leave empty if you don't want any aliases
aliases:
  # The Default command is 'expbottle'.
  # Any changes of main command require
  # server restart.
  main:
  - xpbottle
  - xpb
  - xb
  # Sub-command "give"
  give:
  - i
  # Sub-command "all"
  all:
  - everything
  # Sub-command "reload"
  reload:
  - rel
  help:
  - h
  balance:
  - bal
  for:
  - need